SELECT R.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(v.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO R  JOIN REST_REVIEW V ON R.REST_ID = V.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY v.REST_id
ORDER BY SCORE DESC, FAVORITES DESC;