WITH NAME AS (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC
    LIMIT 1
)

# SELECT A.MEMBER_NAME, B.REVIEW_TEXT, B.REVIEW_DATE
# FROM MEMBER_PROFILE A JOIN REST_REVIEW B JOIN NAME C
# ON A.MEMBER_ID = B.MEMBER_ID = C.MEMBER_ID
# ORDER BY B.REVIEW_DATE, B.REVIEW_TEXT;

SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE A JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
-- [핵심] 1등 ID만 모셔둔 NAME 테이블과 원본 ID를 조인해서 필터링!
JOIN NAME N ON A.MEMBER_ID = N.MEMBER_ID 
ORDER BY B.REVIEW_DATE ASC, B.REVIEW_TEXT ASC;