-- 코드를 작성해주세요


WITH TEMP AS
(   SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO)
SELECT B.SCORE, A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
FROM HR_EMPLOYEES A JOIN TEMP B
ON A.EMP_NO = B.EMP_NO
WHERE B.SCORE = (SELECT MAX(SCORE) FROM TEMP);