WITH TMP AS (
    SELECT EMP_NO, SUM(SCORE) AS MAX_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY SUM(SCORE) DESC
    LIMIT 1
)

SELECT SUM(G.SCORE) AS SCORE,
       E.EMP_NO,
       E.EMP_NAME,
       E.POSITION,
       E.EMAIL
FROM HR_EMPLOYEES E JOIN HR_GRADE G
ON E.EMP_NO = G.EMP_NO
JOIN TMP T ON G.EMP_NO = T.EMP_NO
GROUP BY E.EMP_NO;